version: "3.7"

services: 
  webserver:
    build: 
      context: bin/webserver
    container_name: 'apache'
    ports:
      - "8089:80"
      - "443:443"
    links: 
      - mysql
      - phpmyadmin
    volumes: 
      - ${DOCUMENT_ROOT-./www}:/var/www/html
  mysql:
    build: ./bin/mysql
    container_name: 'mysql'
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: root
      MYSQL_PASSWORD: 123

  phpmyadmin:
    build: ./bin/phpmyadmin
    container_name: 'phpmyadmin'
    ports:
      - '8080:80'
   
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
